### ISSUE TITLE
Update to 1.6.0 fails: No prebuilt binaries found

### ISSUE THREAD

**Issue by iTob191** [Azganoth/tree-sitter-lua#2]
Updating to the latest version of [language-lua-plus](https://github.com/Azganoth/language-lua-plus) (1.6.0) fails with the following error log:

```
> tree-sitter-lua@1.6.0 install %LocalAppData%\Temp\apm-install-dir-119712-19064-1donkpp.b1t6\node_modules\language-lua-plus\node_modules\tree-sitter-lua
> prebuild-install || node-gyp rebuild


%LocalAppData%\Temp\apm-install-dir-119712-19064-1donkpp.b1t6\node_modules\language-lua-plus\node_modules\tree-sitter-lua>if not defined npm_config_node_gyp (node "%LocalAppData%\atom\app-1.39.1\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "%LocalAppData%\atom\app-1.39.1\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (%LocalAppData%\atom\app-1.39.1\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (%LocalAppData%\atom\app-1.39.1\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at %LocalAppData%\atom\app-1.39.1\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "%LocalAppData%\\atom\\app-1.39.1\\resources\\app\\apm\\bin\\node.exe" "%LocalAppData%\\atom\\app-1.39.1\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd %LocalAppData%\Temp\apm-install-dir-119712-19064-1donkpp.b1t6\node_modules\language-lua-plus\node_modules\tree-sitter-lua
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '%LocalAppData%\Temp\apm-install-dir-119712-19064-1donkpp.b1t6\package.json'
npm WARN apm-install-dir-119712-19064-1donkpp.b1t6 No description
npm WARN apm-install-dir-119712-19064-1donkpp.b1t6 No repository field.
npm WARN apm-install-dir-119712-19064-1donkpp.b1t6 No README data
npm WARN apm-install-dir-119712-19064-1donkpp.b1t6 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-lua@1.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-lua@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Using Atom 1.39.1 on Win10 64 bit.

**Comment by Azganoth** [comment]
Oh sorry, i forgot to upload the binaries to Github, you should be able to install it now.

**Comment by iTob191** [comment]
Works fine now. Thanks for the quick resolution!
